//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegralSoft.ConsoleTest.wsServicesCFE {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamEnviarCFE", Namespace="http://IntegralSoft/IntegralCFEService/V001")]
    [System.SerializableAttribute()]
    public partial class ParamEnviarCFE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailPDFDestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SobreCFEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adenda {
            get {
                return this.AdendaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdendaField, value) != true)) {
                    this.AdendaField = value;
                    this.RaisePropertyChanged("Adenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailPDFDestinatario {
            get {
                return this.EmailPDFDestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailPDFDestinatarioField, value) != true)) {
                    this.EmailPDFDestinatarioField = value;
                    this.RaisePropertyChanged("EmailPDFDestinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityToken {
            get {
                return this.SecurityTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityTokenField, value) != true)) {
                    this.SecurityTokenField = value;
                    this.RaisePropertyChanged("SecurityToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SobreCFE {
            get {
                return this.SobreCFEField;
            }
            set {
                if ((object.ReferenceEquals(this.SobreCFEField, value) != true)) {
                    this.SobreCFEField = value;
                    this.RaisePropertyChanged("SobreCFE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultEnviarCFE", Namespace="http://IntegralSoft/IntegralCFEService/V001")]
    [System.SerializableAttribute()]
    public partial class ResultEnviarCFE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntegralSoft.ConsoleTest.wsServicesCFE.ErrorNegocio ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdResultCFEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntegralSoft.ConsoleTest.wsServicesCFE.ErrorNegocio Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdResultCFE {
            get {
                return this.IdResultCFEField;
            }
            set {
                if ((this.IdResultCFEField.Equals(value) != true)) {
                    this.IdResultCFEField = value;
                    this.RaisePropertyChanged("IdResultCFE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorNegocio", Namespace="http://IntegralSoft/IntegralCFEService/V001")]
    [System.SerializableAttribute()]
    public partial class ErrorNegocio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamConsultarCFE", Namespace="http://IntegralSoft/IntegralCFEService/V001")]
    [System.SerializableAttribute()]
    public partial class ParamConsultarCFE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdResultCFEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdResultCFE {
            get {
                return this.IdResultCFEField;
            }
            set {
                if ((this.IdResultCFEField.Equals(value) != true)) {
                    this.IdResultCFEField = value;
                    this.RaisePropertyChanged("IdResultCFE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityToken {
            get {
                return this.SecurityTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityTokenField, value) != true)) {
                    this.SecurityTokenField = value;
                    this.RaisePropertyChanged("SecurityToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultConsultarCFE", Namespace="http://IntegralSoft/IntegralCFEService/V001")]
    [System.SerializableAttribute()]
    public partial class ResultConsultarCFE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntegralSoft.ConsoleTest.wsServicesCFE.ErrorNegocio ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IngresadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntegralSoft.ConsoleTest.wsServicesCFE.ErrorNegocio Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ingresado {
            get {
                return this.IngresadoField;
            }
            set {
                if ((this.IngresadoField.Equals(value) != true)) {
                    this.IngresadoField = value;
                    this.RaisePropertyChanged("Ingresado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://IntegralSoft/IntegralCFEService/V001", ConfigurationName="wsServicesCFE.IServiceFacade")]
    public interface IServiceFacade {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegralSoft/IntegralCFEService/V001/IServiceFacade/EnviarCFE", ReplyAction="http://IntegralSoft/IntegralCFEService/V001/IServiceFacade/EnviarCFEResponse")]
        IntegralSoft.ConsoleTest.wsServicesCFE.ResultEnviarCFE EnviarCFE(IntegralSoft.ConsoleTest.wsServicesCFE.ParamEnviarCFE param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegralSoft/IntegralCFEService/V001/IServiceFacade/ConsultarCFE", ReplyAction="http://IntegralSoft/IntegralCFEService/V001/IServiceFacade/ConsultarCFEResponse")]
        IntegralSoft.ConsoleTest.wsServicesCFE.ResultConsultarCFE ConsultarCFE(IntegralSoft.ConsoleTest.wsServicesCFE.ParamConsultarCFE param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceFacadeChannel : IntegralSoft.ConsoleTest.wsServicesCFE.IServiceFacade, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceFacadeClient : System.ServiceModel.ClientBase<IntegralSoft.ConsoleTest.wsServicesCFE.IServiceFacade>, IntegralSoft.ConsoleTest.wsServicesCFE.IServiceFacade {
        
        public ServiceFacadeClient() {
        }
        
        public ServiceFacadeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceFacadeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFacadeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IntegralSoft.ConsoleTest.wsServicesCFE.ResultEnviarCFE EnviarCFE(IntegralSoft.ConsoleTest.wsServicesCFE.ParamEnviarCFE param) {
            return base.Channel.EnviarCFE(param);
        }
        
        public IntegralSoft.ConsoleTest.wsServicesCFE.ResultConsultarCFE ConsultarCFE(IntegralSoft.ConsoleTest.wsServicesCFE.ParamConsultarCFE param) {
            return base.Channel.ConsultarCFE(param);
        }
    }
}
