//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinAppClient.wsCFEService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamEnviarCFE", Namespace="http://IntegralSoft/IntegralCFEService/V001")]
    [System.SerializableAttribute()]
    public partial class ParamEnviarCFE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailPDFDestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SobreCFEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adenda {
            get {
                return this.AdendaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdendaField, value) != true)) {
                    this.AdendaField = value;
                    this.RaisePropertyChanged("Adenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailPDFDestinatario {
            get {
                return this.EmailPDFDestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailPDFDestinatarioField, value) != true)) {
                    this.EmailPDFDestinatarioField = value;
                    this.RaisePropertyChanged("EmailPDFDestinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityToken {
            get {
                return this.SecurityTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityTokenField, value) != true)) {
                    this.SecurityTokenField = value;
                    this.RaisePropertyChanged("SecurityToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SobreCFE {
            get {
                return this.SobreCFEField;
            }
            set {
                if ((object.ReferenceEquals(this.SobreCFEField, value) != true)) {
                    this.SobreCFEField = value;
                    this.RaisePropertyChanged("SobreCFE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultEnviarCFE", Namespace="http://IntegralSoft/IntegralCFEService/V001")]
    [System.SerializableAttribute()]
    public partial class ResultEnviarCFE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinAppClient.wsCFEService.ErrorNegocio ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdResultCFEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinAppClient.wsCFEService.ErrorNegocio Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdResultCFE {
            get {
                return this.IdResultCFEField;
            }
            set {
                if ((this.IdResultCFEField.Equals(value) != true)) {
                    this.IdResultCFEField = value;
                    this.RaisePropertyChanged("IdResultCFE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorNegocio", Namespace="http://IntegralSoft/IntegralCFEService/V001")]
    [System.SerializableAttribute()]
    public partial class ErrorNegocio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamConsultarCFE", Namespace="http://IntegralSoft/IntegralCFEService/V001")]
    [System.SerializableAttribute()]
    public partial class ParamConsultarCFE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RecepcionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecepcionId {
            get {
                return this.RecepcionIdField;
            }
            set {
                if ((this.RecepcionIdField.Equals(value) != true)) {
                    this.RecepcionIdField = value;
                    this.RaisePropertyChanged("RecepcionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityToken {
            get {
                return this.SecurityTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityTokenField, value) != true)) {
                    this.SecurityTokenField = value;
                    this.RaisePropertyChanged("SecurityToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultConsultarCFE", Namespace="http://IntegralSoft/IntegralCFEService/V001")]
    [System.SerializableAttribute()]
    public partial class ResultConsultarCFE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinAppClient.wsCFEService.DatosRecepcion DatosRecepcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinAppClient.wsCFEService.ErrorNegocio ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinAppClient.wsCFEService.DatosRecepcion DatosRecepcion {
            get {
                return this.DatosRecepcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosRecepcionField, value) != true)) {
                    this.DatosRecepcionField = value;
                    this.RaisePropertyChanged("DatosRecepcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinAppClient.wsCFEService.ErrorNegocio Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosRecepcion", Namespace="http://IntegralSoft/IntegralCFEService/V001")]
    [System.SerializableAttribute()]
    public partial class DatosRecepcion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CAEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CaeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoSeguridadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailPdfDestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnRegimenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FeMovimientoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaGeneracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImpresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NroComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcesadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublicadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublicadoWebField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RE02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RecepcionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ReporteDiarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SobreDGIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SobreEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SobreEmpresaProcesadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo {
            get {
                return this.ArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoField, value) != true)) {
                    this.ArchivoField = value;
                    this.RaisePropertyChanged("Archivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CAE {
            get {
                return this.CAEField;
            }
            set {
                if ((this.CAEField.Equals(value) != true)) {
                    this.CAEField = value;
                    this.RaisePropertyChanged("CAE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CaeId {
            get {
                return this.CaeIdField;
            }
            set {
                if ((this.CaeIdField.Equals(value) != true)) {
                    this.CaeIdField = value;
                    this.RaisePropertyChanged("CaeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoSeguridad {
            get {
                return this.CodigoSeguridadField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoSeguridadField, value) != true)) {
                    this.CodigoSeguridadField = value;
                    this.RaisePropertyChanged("CodigoSeguridad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailPdfDest {
            get {
                return this.EmailPdfDestField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailPdfDestField, value) != true)) {
                    this.EmailPdfDestField = value;
                    this.RaisePropertyChanged("EmailPdfDest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnRegimen {
            get {
                return this.EnRegimenField;
            }
            set {
                if ((object.ReferenceEquals(this.EnRegimenField, value) != true)) {
                    this.EnRegimenField = value;
                    this.RaisePropertyChanged("EnRegimen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fact {
            get {
                return this.FactField;
            }
            set {
                if ((this.FactField.Equals(value) != true)) {
                    this.FactField = value;
                    this.RaisePropertyChanged("Fact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FeMovimientoId {
            get {
                return this.FeMovimientoIdField;
            }
            set {
                if ((this.FeMovimientoIdField.Equals(value) != true)) {
                    this.FeMovimientoIdField = value;
                    this.RaisePropertyChanged("FeMovimientoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaGeneracion {
            get {
                return this.FechaGeneracionField;
            }
            set {
                if ((this.FechaGeneracionField.Equals(value) != true)) {
                    this.FechaGeneracionField = value;
                    this.RaisePropertyChanged("FechaGeneracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Impreso {
            get {
                return this.ImpresoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImpresoField, value) != true)) {
                    this.ImpresoField = value;
                    this.RaisePropertyChanged("Impreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NroComprobante {
            get {
                return this.NroComprobanteField;
            }
            set {
                if ((this.NroComprobanteField.Equals(value) != true)) {
                    this.NroComprobanteField = value;
                    this.RaisePropertyChanged("NroComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Procesado {
            get {
                return this.ProcesadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcesadoField, value) != true)) {
                    this.ProcesadoField = value;
                    this.RaisePropertyChanged("Procesado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publicado {
            get {
                return this.PublicadoField;
            }
            set {
                if ((object.ReferenceEquals(this.PublicadoField, value) != true)) {
                    this.PublicadoField = value;
                    this.RaisePropertyChanged("Publicado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublicadoWeb {
            get {
                return this.PublicadoWebField;
            }
            set {
                if ((object.ReferenceEquals(this.PublicadoWebField, value) != true)) {
                    this.PublicadoWebField = value;
                    this.RaisePropertyChanged("PublicadoWeb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RE02 {
            get {
                return this.RE02Field;
            }
            set {
                if ((object.ReferenceEquals(this.RE02Field, value) != true)) {
                    this.RE02Field = value;
                    this.RaisePropertyChanged("RE02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecepcionId {
            get {
                return this.RecepcionIdField;
            }
            set {
                if ((this.RecepcionIdField.Equals(value) != true)) {
                    this.RecepcionIdField = value;
                    this.RaisePropertyChanged("RecepcionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReporteDiarioId {
            get {
                return this.ReporteDiarioIdField;
            }
            set {
                if ((this.ReporteDiarioIdField.Equals(value) != true)) {
                    this.ReporteDiarioIdField = value;
                    this.RaisePropertyChanged("ReporteDiarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serie {
            get {
                return this.SerieField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieField, value) != true)) {
                    this.SerieField = value;
                    this.RaisePropertyChanged("Serie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SobreDGI {
            get {
                return this.SobreDGIField;
            }
            set {
                if ((object.ReferenceEquals(this.SobreDGIField, value) != true)) {
                    this.SobreDGIField = value;
                    this.RaisePropertyChanged("SobreDGI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SobreEmpresa {
            get {
                return this.SobreEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.SobreEmpresaField, value) != true)) {
                    this.SobreEmpresaField = value;
                    this.RaisePropertyChanged("SobreEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SobreEmpresaProcesado {
            get {
                return this.SobreEmpresaProcesadoField;
            }
            set {
                if ((object.ReferenceEquals(this.SobreEmpresaProcesadoField, value) != true)) {
                    this.SobreEmpresaProcesadoField = value;
                    this.RaisePropertyChanged("SobreEmpresaProcesado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamObtenerRecepcionPorEstado", Namespace="http://IntegralSoft/IntegralCFEService/V001")]
    [System.SerializableAttribute()]
    public partial class ParamObtenerRecepcionPorEstado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CondicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Condicion {
            get {
                return this.CondicionField;
            }
            set {
                if ((object.ReferenceEquals(this.CondicionField, value) != true)) {
                    this.CondicionField = value;
                    this.RaisePropertyChanged("Condicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityToken {
            get {
                return this.SecurityTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityTokenField, value) != true)) {
                    this.SecurityTokenField = value;
                    this.RaisePropertyChanged("SecurityToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultObtenerRecepcionPorEstado", Namespace="http://IntegralSoft/IntegralCFEService/V001")]
    [System.SerializableAttribute()]
    public partial class ResultObtenerRecepcionPorEstado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinAppClient.wsCFEService.ErrorNegocio ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long[] RecepcionIDsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinAppClient.wsCFEService.ErrorNegocio Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] RecepcionIDs {
            get {
                return this.RecepcionIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecepcionIDsField, value) != true)) {
                    this.RecepcionIDsField = value;
                    this.RaisePropertyChanged("RecepcionIDs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://IntegralSoft/IntegralCFEService/V001", ConfigurationName="wsCFEService.IServiceFacade")]
    public interface IServiceFacade {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegralSoft/IntegralCFEService/V001/IServiceFacade/EnviarCFE", ReplyAction="http://IntegralSoft/IntegralCFEService/V001/IServiceFacade/EnviarCFEResponse")]
        WinAppClient.wsCFEService.ResultEnviarCFE EnviarCFE(WinAppClient.wsCFEService.ParamEnviarCFE param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegralSoft/IntegralCFEService/V001/IServiceFacade/EnviarCFE", ReplyAction="http://IntegralSoft/IntegralCFEService/V001/IServiceFacade/EnviarCFEResponse")]
        System.Threading.Tasks.Task<WinAppClient.wsCFEService.ResultEnviarCFE> EnviarCFEAsync(WinAppClient.wsCFEService.ParamEnviarCFE param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegralSoft/IntegralCFEService/V001/IServiceFacade/ConsultarCFE", ReplyAction="http://IntegralSoft/IntegralCFEService/V001/IServiceFacade/ConsultarCFEResponse")]
        WinAppClient.wsCFEService.ResultConsultarCFE ConsultarCFE(WinAppClient.wsCFEService.ParamConsultarCFE param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegralSoft/IntegralCFEService/V001/IServiceFacade/ConsultarCFE", ReplyAction="http://IntegralSoft/IntegralCFEService/V001/IServiceFacade/ConsultarCFEResponse")]
        System.Threading.Tasks.Task<WinAppClient.wsCFEService.ResultConsultarCFE> ConsultarCFEAsync(WinAppClient.wsCFEService.ParamConsultarCFE param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegralSoft/IntegralCFEService/V001/IServiceFacade/ObtenerRecepcionPorEst" +
            "ado", ReplyAction="http://IntegralSoft/IntegralCFEService/V001/IServiceFacade/ObtenerRecepcionPorEst" +
            "adoResponse")]
        WinAppClient.wsCFEService.ResultObtenerRecepcionPorEstado ObtenerRecepcionPorEstado(WinAppClient.wsCFEService.ParamObtenerRecepcionPorEstado param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegralSoft/IntegralCFEService/V001/IServiceFacade/ObtenerRecepcionPorEst" +
            "ado", ReplyAction="http://IntegralSoft/IntegralCFEService/V001/IServiceFacade/ObtenerRecepcionPorEst" +
            "adoResponse")]
        System.Threading.Tasks.Task<WinAppClient.wsCFEService.ResultObtenerRecepcionPorEstado> ObtenerRecepcionPorEstadoAsync(WinAppClient.wsCFEService.ParamObtenerRecepcionPorEstado param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceFacadeChannel : WinAppClient.wsCFEService.IServiceFacade, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceFacadeClient : System.ServiceModel.ClientBase<WinAppClient.wsCFEService.IServiceFacade>, WinAppClient.wsCFEService.IServiceFacade {
        
        public ServiceFacadeClient() {
        }
        
        public ServiceFacadeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceFacadeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFacadeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinAppClient.wsCFEService.ResultEnviarCFE EnviarCFE(WinAppClient.wsCFEService.ParamEnviarCFE param) {
            return base.Channel.EnviarCFE(param);
        }
        
        public System.Threading.Tasks.Task<WinAppClient.wsCFEService.ResultEnviarCFE> EnviarCFEAsync(WinAppClient.wsCFEService.ParamEnviarCFE param) {
            return base.Channel.EnviarCFEAsync(param);
        }
        
        public WinAppClient.wsCFEService.ResultConsultarCFE ConsultarCFE(WinAppClient.wsCFEService.ParamConsultarCFE param) {
            return base.Channel.ConsultarCFE(param);
        }
        
        public System.Threading.Tasks.Task<WinAppClient.wsCFEService.ResultConsultarCFE> ConsultarCFEAsync(WinAppClient.wsCFEService.ParamConsultarCFE param) {
            return base.Channel.ConsultarCFEAsync(param);
        }
        
        public WinAppClient.wsCFEService.ResultObtenerRecepcionPorEstado ObtenerRecepcionPorEstado(WinAppClient.wsCFEService.ParamObtenerRecepcionPorEstado param) {
            return base.Channel.ObtenerRecepcionPorEstado(param);
        }
        
        public System.Threading.Tasks.Task<WinAppClient.wsCFEService.ResultObtenerRecepcionPorEstado> ObtenerRecepcionPorEstadoAsync(WinAppClient.wsCFEService.ParamObtenerRecepcionPorEstado param) {
            return base.Channel.ObtenerRecepcionPorEstadoAsync(param);
        }
    }
}
